require("core.keymaps-conf")
require("core.options-conf")
require("core.plugins-reg-conf")
require("config.mason")
require("config.lsp")
require("config.blink")
require("config.treesiter")
vim.cmd[[colorscheme cyberdream]]
require("nvim-autopairs").setup()
require("telescope").setup()
require("ibl").setup()
